name: task-delegation
version: 1.2.0
description: Delegate user stories with complete context, clear acceptance criteria, and validation
author: Vineeth Soma
type: skill

dependencies:
  apm:
    - vineethsoma/agent-packages/skills/spec-driven-development
