name: fullstack-expertise
version: 1.1.0
description: Backend, frontend, database, DevOps, testing, and integration validation domain knowledge for full-stack development
author: Vineeth Soma
type: skill
