name: spec-driven-development
version: 1.1.0
description: Spec-Driven Development workflow using GitHub spec-kit for building high-quality software with structured specifications
author: Vineeth Soma
type: skill
