name: tdd-workflow
version: 1.3.0
description: Test-Driven Development workflow with TDD commit convention, compliance tracking, validation, and mandatory integration testing
author: Vineeth Soma
type: skill
