name: feature-orchestration
version: 1.2.0
description: Story orchestration with progress tracking, standardized directory structure, and validation
author: Vineeth Soma
type: skill

dependencies:
  apm:
    - vineethsoma/agent-packages/skills/spec-driven-development
    - vineethsoma/agent-packages/skills/git-worktree-workflow
